version: '3.7'
services:
  udyme-office:
    container_name: udyme-office
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "8887:80"
    networks:
      - udyme-office
    restart: always
networks:
  udyme-office:
    driver: bridge
